# Generated by Django 5.0.9 on 2024-10-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['order', 'featured', '-updated']},
        ),
        migrations.RenameField(
            model_name='subscriptionprice',
            old_name='orders',
            new_name='order',
        ),
    ]
